### ISSUE TITLE
nhuduoibaut

### ISSUE THREAD

**Issue by dumsharktm2007** [ItzDenkiRepo/DMHEROTEAM.ML#2]
cringe vai lon, content thi an cap, nham lon, choi genshit ma dell biet thu bo cua co ban la cac nguyen to
noi chung la nhu cc t

**Comment by NgTienBut** [comment]
cringe

**Comment by thedtvn** [comment]
cringe

**Comment by honaki-dev** [comment]
nhu cac :))
